# -*- coding: utf-8 -*-
"""WhatsApp automation using selenium.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tL4XzzPlwtS6G3ODF7w9VSd6z1lM6iuc
"""

from selenium import webdriver

browser=webdriver.Chrome("/Users/Desktop/chromedriver")

browser.get("https://www.selenium.dev/")

download=browser.find_element_by_link_text("Downloads")

search=browser.find_element_by_id('gsc-i-id1')
serch.send_keys("Downloads")

#whatsapp automation

from selenium import webdriver

from selenium.webdriver.support import expected_conditions as ec

from selenium.webdriver.support.ui import WebDriverWait

from selenium.webdriver.common.keys import Keys

from selenium.webdriver.common.by import By
import time

browser=webdrive.Chrome("/Users/Desktop/chromedriver")

browser.get("https://web.whatsapp.com")

wait=WebDriverWait(browser,600)

#for sending message

target="Aditya"
string="hello"
#enter the span code
x_arg="//span[]"
target=wait.until(ec.presence_of_element_located(By.XPATH,x_arg))

target.click()

#enter the class code of your whatsapp
input_box=browser.find_element_by_class_name("class code")

#send message for 50 times

for i in range(50):
  input_box.send_Keys(string+Keys.ENTER)